version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i npm@latest -g
      - npm cache clean --force
      - rm -rf node_modules package-lock.json
  pre_build:
    commands:
      - npm install
      - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
  post_build:
    commands:
      - python scripts/create-image-defintion.py imagedefinitions.json $CONTAINER_NAME $ECR_REGISTRY/$ECR_REPOSITORY:latest
artifacts:
  files:
    - imagedefinitions.json
